const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const langBtn=$('#langBtn'), nav=$('#nav'), menu=$('#menuBtn'); let lang='en';
function setLanguage(l){lang=l;document.documentElement.lang=l;document.documentElement.dir=l==='ar'?'rtl':'ltr';langBtn.textContent=l==='ar'?'EN':'AR';$$('[data-en][data-ar]').forEach(el=>{el.innerHTML=el.dataset[l]});localStorage.setItem('tiamo-lang',l)}
langBtn.addEventListener('click',()=>setLanguage(lang==='en'?'ar':'en'));menu?.addEventListener('click',()=>nav.classList.toggle('open'));
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(e=>obs.observe(e));
$$('.slider').forEach(slider=>{const track=slider.querySelector('.slides'), items=[...slider.querySelectorAll('.slides figure')], dots=slider.querySelector('.dots');let i=0,timer,paused=false;items.forEach((_,n)=>{const d=document.createElement('button');d.ariaLabel=`Slide ${n+1}`;d.onclick=()=>go(n);dots.appendChild(d)});const update=()=>{track.style.transform=`translateX(-${i*100}%)`;[...dots.children].forEach((d,n)=>d.classList.toggle('active',n===i))};function go(n){i=(n+items.length)%items.length;update();restart()}function next(){go(i+1)}function restart(){clearInterval(timer);timer=setInterval(()=>{if(!paused)next()},Number(slider.dataset.delay)||4000)}slider.querySelector('.next').onclick=next;slider.querySelector('.prev').onclick=()=>go(i-1);slider.addEventListener('mouseenter',()=>paused=true);slider.addEventListener('mouseleave',()=>paused=false);slider.addEventListener('focusin',()=>paused=true);slider.addEventListener('focusout',()=>paused=false);let sx=0;slider.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});slider.addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)go(i+(dx<0?1:-1))},{passive:true});update();restart()});
const glow=$('.cursor-glow');window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
const canvas=$('#particles'),ctx=canvas.getContext('2d');let pts=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;pts=Array.from({length:Math.min(70,Math.floor(innerWidth/18))},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.25,r:Math.random()*1.5+.3}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='rgba(173,126,255,.6)';pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>canvas.width)p.vx*=-1;if(p.y<0||p.y>canvas.height)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw();
setLanguage(localStorage.getItem('tiamo-lang')||'en');
